hit_rate += argument1; //闁告稒鍨濋懙鎴︽偝?
evade += argument2; //闂傚偆浜导?
brain += argument3; //闁哄懎鎼慨?
potence += argument4; //闁告梹鐩崳?
criti += argument5;// 闁哄棙娼欓崵顕€鎮?
critical += argument6; //闁哄棛绻濆┑鈧?
yellow += argument7;
skillpower += argument8;
var a = instance_create(x,y,obj_time_buff);
a.hit_rate = argument1; //闁告稒鍨濋懙鎴︽偝?
a.evade = argument2; //闂傚偆浜导?
a.brain = argument3; //闁哄懎鎼慨?
a.potence = argument4; //闁告梹鐩崳?
a.criti = argument5;// 闁哄棙娼欓崵顕€鎮?
a.critical = argument6; //闁哄棛绻濆┑鈧?
a.yellow = argument7;
a.skillpower = argument8;
a.time = argument0;